// <auto-generated />
using System;
using CryptoAppBackEnd.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CryptoApp.Infrastructure.Infraestructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CryptoAppBackEnd.Infraestructure.Persistence.Models.CryptoCurrencyDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("current_price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("image_url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("last_price_update")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("market_cap")
                        .HasPrecision(24, 2)
                        .HasColumnType("numeric(24,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("price_change_24h")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("symbol")
                        .IsUnique();

                    b.ToTable("crypto_currencies", (string)null);
                });

            modelBuilder.Entity("CryptoAppBackEnd.Infraestructure.Persistence.Models.MovementDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("crypto_id")
                        .HasColumnType("integer");

                    b.Property<int>("person_id")
                        .HasColumnType("integer");

                    b.Property<int>("portfolio_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("realized_pnl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<char>("type")
                        .HasColumnType("character(1)");

                    b.HasKey("id");

                    b.HasIndex("crypto_id");

                    b.HasIndex("person_id");

                    b.HasIndex("portfolio_id");

                    b.ToTable("movements", (string)null);
                });

            modelBuilder.Entity("CryptoAppBackEnd.Infraestructure.Persistence.Models.PersonDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("role")
                        .HasColumnType("character(1)");

                    b.Property<bool>("status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("CryptoAppBackEnd.Infraestructure.Persistence.Models.PortfolioAssetDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("average_buy_price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("crypto_id")
                        .HasColumnType("integer");

                    b.Property<int>("portfolio_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("total_invested")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("crypto_id");

                    b.HasIndex("portfolio_id");

                    b.ToTable("portfolio_assets", (string)null);
                });

            modelBuilder.Entity("CryptoAppBackEnd.Infraestructure.Persistence.Models.PortfolioDbModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("base_currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("person_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("person_id");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("CryptoAppBackEnd.Infraestructure.Persistence.Models.MovementDbModel", b =>
                {
                    b.HasOne("CryptoAppBackEnd.Infraestructure.Persistence.Models.CryptoCurrencyDbModel", null)
                        .WithMany()
                        .HasForeignKey("crypto_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoAppBackEnd.Infraestructure.Persistence.Models.PersonDbModel", null)
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoAppBackEnd.Infraestructure.Persistence.Models.PortfolioDbModel", null)
                        .WithMany()
                        .HasForeignKey("portfolio_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoAppBackEnd.Infraestructure.Persistence.Models.PortfolioAssetDbModel", b =>
                {
                    b.HasOne("CryptoAppBackEnd.Infraestructure.Persistence.Models.CryptoCurrencyDbModel", null)
                        .WithMany()
                        .HasForeignKey("crypto_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CryptoAppBackEnd.Infraestructure.Persistence.Models.PortfolioDbModel", null)
                        .WithMany()
                        .HasForeignKey("portfolio_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CryptoAppBackEnd.Infraestructure.Persistence.Models.PortfolioDbModel", b =>
                {
                    b.HasOne("CryptoAppBackEnd.Infraestructure.Persistence.Models.PersonDbModel", null)
                        .WithMany()
                        .HasForeignKey("person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
